# Generated by Django 6.0.5 on 2026-05-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
